name: ramp-meg
channels:
  - defaults
dependencies:
  - python >=3.7
  - jupyterlab
  - numpy
  - scikit-learn >=0.22
  - scipy
  - pandas
  - matplotlib
  - pip
  - pip:
    - ramp-workflow
    - ramp-utils
    - pot
    - imbalanced-learn
