echo "================================="
echo "GENERATING DATA FOR LEFT AUDITORY"
echo "================================="
python plot_for_tex_2.py --estimator lasso-cv --condition "Left Auditory"
python plot_for_tex_2.py --estimator lasso-sure --condition "Left Auditory"
python plot_for_tex_2.py --estimator adaptive-cv --condition "Left Auditory"
python plot_for_tex_2.py --estimator adaptive-sure --condition "Left Auditory"

echo "=================================="
echo "GENERATING DATA FOR RIGHT AUDITORY"
echo "=================================="
python plot_for_tex_2.py --estimator lasso-cv --condition "Right Auditory"
python plot_for_tex_2.py --estimator lasso-sure --condition "Right Auditory"
python plot_for_tex_2.py --estimator adaptive-cv --condition "Right Auditory"
python plot_for_tex_2.py --estimator adaptive-sure --condition "Right Auditory"

echo "==============================="
echo "GENERATING DATA FOR LEFT VISUAL"
echo "==============================="
python plot_for_tex_2.py --estimator lasso-cv --condition "Left visual"
python plot_for_tex_2.py --estimator lasso-sure --condition "Left visual"
python plot_for_tex_2.py --estimator adaptive-cv --condition "Left visual"
python plot_for_tex_2.py --estimator adaptive-sure --condition "Left visual"

echo "================================"
echo "GENERATING DATA FOR RIGHT VISUAL"
echo "================================" 
python plot_for_tex_2.py --estimator lasso-cv --condition "Right visual"
python plot_for_tex_2.py --estimator lasso-sure --condition "Right visual"
python plot_for_tex_2.py --estimator adaptive-cv --condition "Right visual"
python plot_for_tex_2.py --estimator adaptive-sure --condition "Right visual"
